# استفاده از تصویر سبک پایتون
FROM python:3.10-slim

# تنظیم دایرکتوری کاری
WORKDIR /app

# نصب ابزارهای موردنیاز برای اجرای OpenCV و دیگر وابستگی‌ها
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    pkg-config \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgl1-mesa-glx \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libv4l-dev \
    libxvidcore-dev \
    libx264-dev \
    libatlas-base-dev \
    gfortran \
    openssl \  # اضافه کردن openssl برای SSL
    && rm -rf /var/lib/apt/lists/*

# کپی و نصب وابستگی‌ها
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# کپی کردن تمام فایل‌های پروژه
COPY . .

# باز کردن پورت پیش‌فرض Flask
EXPOSE 5000

# اجرای اپلیکیشن Flask
CMD ["python", "server.py"]
