# استفاده از تصویر سبک پایتون
FROM python:3.10-slim

# تنظیم یک دایرکتوری کاری در کانتینر
WORKDIR /app

# نصب ابزارهای ضروری برای اجرای کتابخانه‌ها (در صورت نیاز)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

# کپی فایل requirements.txt برای نصب وابستگی‌ها
COPY requirements.txt .

# نصب وابستگی‌های پروژه
RUN pip install --no-cache-dir -r requirements.txt

# کپی کردن تمام فایل‌های پروژه
COPY . .

# باز کردن پورت پیش‌فرض Flask
EXPOSE 5000

# دستور اجرای اپلیکیشن Flask
CMD ["python", "server.py"]
